spring.application.name=locadora-veiculos
spring.datasource.url=jdbc:postgresql://localhost:5432/locadora_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true